### PR TITLE
Add c++ implementation of mbcb

### PR DESCRIPTION
**Pull request by kjakobse**
- The c++ implementation supports sample weights and calculation of standard errors.
- Package structure updated to use the Rcpp interface.

### CODE REVIEW

**Review by jeroenhoogland — CHANGES_REQUESTED** [review]
Thanks a lot for writing a (much) faster implementation supporting sampling weights and SE. With respect to the latter, from the code I gather it's an asymptotic SE assuming p0 and p1 are available without error. It seems of by a factor 2 however (twice as big); would you agree? When checked/corrected I will merge. Thanks again!

**Comment by kjakobse** [comment]
The standard error is based on section 5 in Quade, D. (1971). Nonparametric partial correlation. Stichting Mathematisch Centrum. Mathematische Statistiek. Stichting Mathematisch Centrum. 
The implementation is based on the cidxcn subroutine from the Hmisc R-package (https://github.com/harrelfe/Hmisc/blob/master/src/ratfor/cidxcn.r). 
You are correct that the standard error is off by a factor of 2. This is because cidxcn calculates the standard error of 2(C-index - 0.5), a fact that I failed to notice.

**Review by jeroenhoogland — APPROVED** [review]
Thanks for the added reference and the adjustment of the s.e. code to reflect things on the C scale rather than de Dxy scale! I'll make sure to add the ref to the documentation.

**Comment by jeroenhoogland** [comment]
Many thank to kjacobse for adding a (much) faster c++ implementation for the mbcb with added support for sample weights and calculation of standard errors.

**Pull request merged**
